name: Teste com Banco de Dados
on: [push, pull_request]

jobs:
  db-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
        # Aguarda o banco estar pronto para uso
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Testar conexão (Exemplo)
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=mysecretpassword psql -h localhost -U postgres -c "SELECT 1;"

